name: pinn-rd-2dt
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11.15
  - pip
  - numpy=2.4.3
  - scipy=1.17.1
  - pandas=3.0.2
  - matplotlib=3.10.8
  - sympy=1.14.0
  - pytorch=2.5.1
  - jupyterlab
  - notebook
  - ipykernel
  - dill
  - imageio
  - pip:
      - pysr==1.5.10
